
export const cardImages: Record<string, any> = {
"0": require('../assets/images/cards/0.png'),
"1": require('../assets/images/cards/1.png'),
"2": require('../assets/images/cards/2.png'),
"3": require('../assets/images/cards/3.png'),
"4": require('../assets/images/cards/4.png'),
"5": require('../assets/images/cards/5.png'),
"6": require('../assets/images/cards/6.png'),
"7": require('../assets/images/cards/7.png'),
"8": require('../assets/images/cards/8.png'),
"9": require('../assets/images/cards/9.png'),
"10": require('../assets/images/cards/10.png'),
"11": require('../assets/images/cards/11.png'),
"12": require('../assets/images/cards/12.png'),
"13": require('../assets/images/cards/13.png'),
"14": require('../assets/images/cards/14.png'),
"15": require('../assets/images/cards/15.png'),
"16": require('../assets/images/cards/16.png'),
"17": require('../assets/images/cards/17.png'),
"18": require('../assets/images/cards/18.png'),
"19": require('../assets/images/cards/19.png'),
"20": require('../assets/images/cards/20.png'),
"21": require('../assets/images/cards/21.png'),
};
